name: TestDeploy

on:
  push:
    branches:
      - master # 你想部署的分支
  workflow_dispatch:
    inputs:
      branch: 
        description: 'Branch to build'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
     PROD_EC2_USER: ${{ secrets.PROD_EC2_USER }}
     PROD_EC2_PUBLIC_DNS: ${{ secrets.PROD_EC2_PUBLIC_DNS }}
     PROD_EC2_STANDBY_PUBLIC_DNS: ${{ secrets.PROD_EC2_STANDBY_PUBLIC_DNS }}
     IMAGE_TAG: ${{ github.sha }}
     ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_DEV_SSH_KEY }}
      
      - name: PRINT configurations
        run: |
          node -e "const fs = require('fs');const envVar = process.env.PROD_EC2_USER || 'default-value';const base64Value = Buffer.from(envVar).toString('base64');fs.writeFileSync('output.txt', base64Value);console.log('Wrote Base64: ' + base64Value + ' to output.txt');"
          cat output.txt
